language: python

python:
  - "3.8"

services:
  - docker

before_install:
  - echo "Installing ngrok"
  
  # Install dependencies for FastAPI
  - pip install python-dotenv

  # Download and unzip ngrok
  - wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
  - unzip ngrok-stable-linux-amd64.zip

  # Move ngrok to /usr/local/bin so it can be globally accessed
  - sudo mv ngrok /usr/local/bin/
  - chmod +x /usr/local/bin/ngrok

  # Verify ngrok installation
  - ngrok --version

  # Authenticate ngrok with your token
  - ngrok authtoken 2q9MJXp3ds13RIQlKeMDKkimCLS_7BqcrUfan8LUZiWHFKT2Z

install:
  - pip install -r requirements.txt

script:
  # Start FastAPI application in the background
  - uvicorn receiver:app --reload --host 0.0.0.0 --port 8000 &
  
  # Wait for FastAPI to start
  - echo "Waiting for FastAPI to start..."
  - sleep 15

  # Start ngrok to expose port 8000
  - ngrok http 8000 &
  - echo "Waiting for ngrok to establish connection..."
  - sleep 20

  # Ensure ngrok is running and retrieve the public URL
  - export RECEIVER_NGROK_URL=$(curl -s http://localhost:4040/api/tunnels | jq -r '.tunnels[0].public_url')

  # Check if ngrok URL retrieval was successful
  - echo "Ngrok URL: $RECEIVER_NGROK_URL"

after_success:
  - echo "Sending request to ngrok URL"
  - curl "$RECEIVER_NGROK_URL/attack"
