language: python

python:
  - "3.8"

services:
  - docker

before_install:
  # Install dependencies for FastAPI
  - pip install python-dotenv

  # Install Cloudflare Tunnel CLI
  - echo "Installing Cloudflare Tunnel CLI"
  - curl -s https://pkg.cloudflare.com/cloudflare-tunnel.sh | sh

  # Authenticate Cloudflare CLI with the provided API token
  - echo "Authenticating with Cloudflare Tunnel"
  - export CLOUDFLARE_API_TOKEN="Ol8FZi4nP2L1tCJN5Q5WLHKVNs0s8HdQMYCWIzPC"
  - cloudflared login

install:
  - pip install -r requirements.txt

script:
  # Start FastAPI application in the background
  - uvicorn receiver:app --reload --host 0.0.0.0 --port 8000 &

  # Wait for FastAPI to start
  - echo "Waiting for FastAPI to start..."
  - sleep 15

  # Start Cloudflare Tunnel to expose port 8000
  - echo "Starting Cloudflare Tunnel to expose FastAPI instance"
  - cloudflared tunnel --url http://localhost:8000 &

after_success:
  # Log confirmation that Cloudflare Tunnel is running
  - echo "Cloudflare Tunnel has been successfully set up and traffic is routed"
  - echo "Application exposed to Cloudflare infrastructure"
